[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "streetworld"
description = "StreetWorld is built on MetaDrive, integrating Gaussian splatting rendering and simulation. It discovers scenes automatically from a scene-config directory and supports remote visualization in a client/server mode for interactive driving or RL training."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "lllcccfff", email = "7802220128@csu.edu.cn" },
    { name = "Jesse Senior", email = "jessesenior@outlook.com" },
]
requires-python = ">=3.8"
version = "0.0.1"
dependencies = [
    "addict",
    "cuda-python<=12.8",
    "glfw",
    "gymnasium",
    "grpcio",
    "grpcio-tools",
    "imgui-bundle",
    "lxml",
    "mediapy",
    "opencv-python-headless",
    "panda3d",
    "pydantic",
    "pygame",
    "PyOpenGL",
    "PyOpenGL_accelerate",
    "protobuf",
    "rich",
    "shapely",
    "torch",
    "trajdata",
    "websockets<14",
    "pyglm",
    "gsplat==1.5.3",
    "plyfile==1.1.3"
]

[tool.setuptools]
packages = [
    "streetworld",
    "streetworld.misc",
    "streetworld.misc.nurec_interface",
    "streetworld.misc.nurec_interface.nre",
    "streetworld.misc.nurec_interface.nre.grpc",
    "streetworld.misc.nurec_interface.nre.grpc.protos",
]

[tool.setuptools.package-dir]
"streetworld" = "streetworld"

[tool.setuptools.package-data]
"streetworld" = ["*", "**/*"]
"streetworld.misc.nurec_interface.nre.grpc.protos" = ["*.proto", "*.pyi"]
