[build-system]
requires = ["setuptools>=45"]
build-backend = "setuptools.build_meta"

[project]
name = "metadrive-simulator"
description = "StreetWorld is built on MetaDrive, integrating Gaussian splatting rendering and simulation. It discovers scenes automatically from a scene-config directory and supports remote visualization in a client/server mode for interactive driving or RL training."
readme = { file = "README.md", content-type = "text/markdown" }
authors = [
    { name = "lllcccfff", email = "7802220128@csu.edu.cn" },
    { name = "Jesse Senior", email = "jessesenior@outlook.com" },
]
requires-python = ">=3.8"
version = "0.0.1"
dependencies = [
    "addict==2.4.0",
    "cuda-python<=12.8",
    "glfw==2.8.0",
    "gymnasium==1.2.0",
    "imgui-bundle==1.6.2",
    "lxml==6.0.2",
    "opencv-python==4.10.0.84",
    "opencv-python-headless==4.11.0.86",
    "panda3d==1.10.15",
    "pydantic==2.12.5",
    "pygame==2.6.1",
    "PyOpenGL==3.1.9",
    "rich==13.8.0",
    "zarr==3.1.5",
    "ninja==1.11.1.1",
    "shapely==2.0.7",
    "geopandas==1.1.2",
    "kornia==0.8.1",
    "seaborn==0.12.1",
    "bokeh==3.8.2",
    "dill==0.4.0",
    "pyarrow==22.0.0",
    "nvdiffrast @ git+https://github.com/NVlabs/nvdiffrast.git@253ac4f",
    "simple-nurec-viewer @ git+https://github.com/Project-Street/simple-nurec-viewer.git@0739ffbb",
    "websockets<14",
    "numpy==1.26.4",
    "grpcio==1.50.0",
    "grpcio-tools==1.50.0",
    "protobuf==4.25.8",
    "huggingface-hub==0.31.4"

]

[tool.setuptools]
packages = ["metadrive"]

[tool.setuptools.package-dir]
"metadrive" = "metadrive"

[tool.setuptools.package-data]
"metadrive" = ["*", "**/*"]
