syntax = "proto3";
import "google/protobuf/struct.proto";

import "common.proto";

// Step request
message StepRequest {
    repeated float action = 1;  // [steering, throttle] normalized to [-1, 1]
}

// Step response
message StepResponse {
    bool status = 1; // 0 is success, 1 is error
    string message = 2; // explain error reason, None for success
    Observation observation = 3;
    float reward = 4;
    bool terminated = 5;
    bool truncated = 6;
    google.protobuf.Struct StepInfo = 7;

}


// Reset request
message ResetRequest {
    string transforms_json_path = 1;
    string render_server_url = 2;  // HTTP address of Gaussian renderer
}

// Reset response
message ResetResponse {
    bool status = 1; // 0 is success, 1 is error
    string message = 2; // explain error reason, None for success
    Observation observation = 3;
    google.protobuf.Struct StepInfo = 4;
}

// Service definition
service EnvService {
    rpc Reset(ResetRequest) returns (ResetResponse);
    rpc Step(StepRequest) returns (StepResponse);
}
