import copy
import logging
import uuid
import gymnasium as gym
import numpy as np
from streetworld.base_class.configurable import Configurable
from streetworld.base_class.randomizable import Randomizable


class BasePolicy(Randomizable, Configurable):
    DEBUG_MARK_COLOR = (255, 255, 255, 255)
    DEBUG_MARK_MODEL = None
    SYNC_DEBUG_MARK_POS_TASK_NAME = "policy_mark"

    def __init__(self, step_manager, config=None):
        Configurable.__init__(self, config)
        Randomizable.__init__(self, 0)
        self.step_manager = step_manager
        self.out_of_road_threshold = config.get("out_of_road_threshold", 5)
        self.arrive_speed_threshold = float(config.get("arrive_speed_threshold", 10.0))
        self.action_info = dict()

    def reset(self, controller, seed, state, init_state, **kwargs):
        self.controller = controller
        self.seed(seed)

        timestamp_list = sorted(state.keys())
        self.spawn_timestamp = timestamp_list[0]

        self.trajectory = state
        self.destination = init_state["destination"]
        self.destination_heading = float(init_state["destination_yaw"])
        self.destination_forward = np.asarray(
            [np.cos(self.destination_heading), np.sin(self.destination_heading)],
            dtype=np.float32,
        )
        self.destination_lateral = np.asarray(
            [-self.destination_forward[1], self.destination_forward[0]],
            dtype=np.float32,
        )
        self.destination_xy = np.asarray(self.destination, dtype=np.float32)[:2]
        valid_timestamps = [timestamp for timestamp in timestamp_list if self.trajectory[timestamp]["valid"]]
        if len(valid_timestamps) == 0:
            raise ValueError("BasePolicy reset got trajectory with no valid states.")
        last_state = self.trajectory[valid_timestamps[-1]]
        self.destination_speed = float(np.linalg.norm(np.asarray(last_state["velocity"], dtype=np.float32)[:2]))
        self.static = sum(
            [np.linalg.norm(traj["velocity"]) for traj in self.trajectory.values()]
        ) / len(self.trajectory) < 0.01

    def act(self, *args, **kwargs):
        """
        Return an action vector consisting of two element: [steering, throttle/brake]. Runtime information generated by
        the policy can be written to self.action_info, which will be retrieved and shown in info dict automatically.
        """
        pass

    @property
    def is_arrive(self):
        if self.static:
            return False
        rel = np.asarray(self.controller.position, dtype=np.float32)[:2] - self.destination_xy
        longitudinal = float(np.dot(rel, self.destination_forward))
        lateral = abs(float(np.dot(rel, self.destination_lateral)))
        speed_error = abs(float(self.controller.speed) - self.destination_speed)
        return longitudinal >= 0.0 and lateral <= 20.0 and speed_error <= self.arrive_speed_threshold

    @property
    def is_spawned(self):
        return self.step_manager.current_timestamp >= self.spawn_timestamp
    
    def get_action_info(self):
        """
        Get current action info for env.step() retrieve
        """
        return copy.deepcopy(self.action_info)

    def destroy(self):
        """
        Destroy Base class
        """
        Configurable.destroy(self)
        Randomizable.destroy(self)

    @property
    def name(self):
        return self.__class__.__name__

    def __repr__(self):
        return self.name

    @classmethod
    def get_input_space(cls):
        """
        It defines the input space of this class of policy. This will be the action space for the agent.
        """
        return gym.spaces.Box(-1.0, 1.0, shape=(2, ), dtype=np.float32)

    def get_state(self):
        return self.get_action_info()
