# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import remote_viewer_pb2 as remote__viewer__pb2


class OnsiteViewerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SendAction = channel.unary_unary(
                '/onsite.viewer.OnsiteViewerService/SendAction',
                request_serializer=remote__viewer__pb2.Action.SerializeToString,
                response_deserializer=remote__viewer__pb2.Image.FromString,
                )


class OnsiteViewerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SendAction(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_OnsiteViewerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SendAction': grpc.unary_unary_rpc_method_handler(
                    servicer.SendAction,
                    request_deserializer=remote__viewer__pb2.Action.FromString,
                    response_serializer=remote__viewer__pb2.Image.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'onsite.viewer.OnsiteViewerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class OnsiteViewerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SendAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/onsite.viewer.OnsiteViewerService/SendAction',
            remote__viewer__pb2.Action.SerializeToString,
            remote__viewer__pb2.Image.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
