# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from streetworld.misc.nurec_interface.nre.grpc.protos import common_pb2 as streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2
from streetworld.misc.nurec_interface.nre.grpc.protos import sensorsim_pb2 as streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2


class SensorsimServiceStub(object):
    """//////////////////////////////////////////////////////////////////////////////
    Sensor simulator <-> Runtime
    //////////////////////////////////////////////////////////////////////////////

    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.render_rgb = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/render_rgb',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderReturn.FromString,
                )
        self.batch_render_rgb = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/batch_render_rgb',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderReturn.FromString,
                )
        self.render_lidar = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/render_lidar',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderReturn.FromString,
                )
        self.get_version = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_version',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.VersionId.FromString,
                )
        self.get_available_scenes = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_available_scenes',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.AvailableScenesReturn.FromString,
                )
        self.get_available_cameras = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_available_cameras',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasReturn.FromString,
                )
        self.shut_down = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/shut_down',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                )
        self.get_available_trajectories = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_available_trajectories',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesReturn.FromString,
                )
        self.get_available_ego_masks = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_available_ego_masks',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableEgoMasksReturn.FromString,
                )
        self.get_external_asset_objects = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_external_asset_objects',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsReturn.FromString,
                )
        self.edit_assets = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/edit_assets',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsResponse.FromString,
                )
        self.restore_model_parameters = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/restore_model_parameters',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RestoreModelParametersRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                )
        self.get_dynamic_objects = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_dynamic_objects',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsRequest.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsReturn.FromString,
                )
        self.get_server_config = channel.unary_unary(
                '/nre.grpc.protos.sensorsim.SensorsimService/get_server_config',
                request_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
                response_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ServerConfig.FromString,
                )


class SensorsimServiceServicer(object):
    """//////////////////////////////////////////////////////////////////////////////
    Sensor simulator <-> Runtime
    //////////////////////////////////////////////////////////////////////////////

    """

    def render_rgb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def batch_render_rgb(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def render_lidar(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_version(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_available_scenes(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_available_cameras(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def shut_down(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_available_trajectories(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_available_ego_masks(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_external_asset_objects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def edit_assets(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def restore_model_parameters(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_dynamic_objects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def get_server_config(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SensorsimServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'render_rgb': grpc.unary_unary_rpc_method_handler(
                    servicer.render_rgb,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderReturn.SerializeToString,
            ),
            'batch_render_rgb': grpc.unary_unary_rpc_method_handler(
                    servicer.batch_render_rgb,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderReturn.SerializeToString,
            ),
            'render_lidar': grpc.unary_unary_rpc_method_handler(
                    servicer.render_lidar,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderReturn.SerializeToString,
            ),
            'get_version': grpc.unary_unary_rpc_method_handler(
                    servicer.get_version,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.VersionId.SerializeToString,
            ),
            'get_available_scenes': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_scenes,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.AvailableScenesReturn.SerializeToString,
            ),
            'get_available_cameras': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_cameras,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasReturn.SerializeToString,
            ),
            'shut_down': grpc.unary_unary_rpc_method_handler(
                    servicer.shut_down,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            ),
            'get_available_trajectories': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_trajectories,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesReturn.SerializeToString,
            ),
            'get_available_ego_masks': grpc.unary_unary_rpc_method_handler(
                    servicer.get_available_ego_masks,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableEgoMasksReturn.SerializeToString,
            ),
            'get_external_asset_objects': grpc.unary_unary_rpc_method_handler(
                    servicer.get_external_asset_objects,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsReturn.SerializeToString,
            ),
            'edit_assets': grpc.unary_unary_rpc_method_handler(
                    servicer.edit_assets,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsResponse.SerializeToString,
            ),
            'restore_model_parameters': grpc.unary_unary_rpc_method_handler(
                    servicer.restore_model_parameters,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RestoreModelParametersRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            ),
            'get_dynamic_objects': grpc.unary_unary_rpc_method_handler(
                    servicer.get_dynamic_objects,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsRequest.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsReturn.SerializeToString,
            ),
            'get_server_config': grpc.unary_unary_rpc_method_handler(
                    servicer.get_server_config,
                    request_deserializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
                    response_serializer=streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ServerConfig.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'nre.grpc.protos.sensorsim.SensorsimService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class SensorsimService(object):
    """//////////////////////////////////////////////////////////////////////////////
    Sensor simulator <-> Runtime
    //////////////////////////////////////////////////////////////////////////////

    """

    @staticmethod
    def render_rgb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/render_rgb',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RGBRenderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def batch_render_rgb(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/batch_render_rgb',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.BatchRGBRenderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def render_lidar(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/render_lidar',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.LidarRenderReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_version(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_version',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.VersionId.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_available_scenes(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_available_scenes',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.AvailableScenesReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_available_cameras(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_available_cameras',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableCamerasReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def shut_down(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/shut_down',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_available_trajectories(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_available_trajectories',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableTrajectoriesReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_available_ego_masks(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_available_ego_masks',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableEgoMasksReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_external_asset_objects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_external_asset_objects',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ExternalAssetObjectsReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def edit_assets(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/edit_assets',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.EditAssetsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def restore_model_parameters(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/restore_model_parameters',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.RestoreModelParametersRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_dynamic_objects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_dynamic_objects',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsRequest.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.AvailableDynamicObjectsReturn.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def get_server_config(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/nre.grpc.protos.sensorsim.SensorsimService/get_server_config',
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_common__pb2.Empty.SerializeToString,
            streetworld_dot_misc_dot_nurec__interface_dot_nre_dot_grpc_dot_protos_dot_sensorsim__pb2.ServerConfig.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
