# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x1a\x1cgoogle/protobuf/struct.proto\"2\n\x06Matrix\x12\x0c\n\x04\x64\x61ta\x18\x01 \x03(\x01\x12\x0c\n\x04rows\x18\x02 \x01(\x05\x12\x0c\n\x04\x63ols\x18\x03 \x01(\x05\"d\n\x0b\x43\x61meraImage\x12\x13\n\x0b\x63\x61mera_name\x18\x01 \x01(\t\x12\x12\n\nimage_data\x18\x02 \x01(\x0c\x12,\n\x0b\x63\x61mera_info\x18\x03 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x86\x01\n\x0bObservation\x12(\n\x12images_observation\x18\x01 \x03(\x0b\x32\x0c.CameraImage\x12\x37\n\x11other_observation\x18\x02 \x01(\x0b\x32\x17.google.protobuf.StructH\x00\x88\x01\x01\x42\x14\n\x12_other_observationb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _MATRIX._serialized_start=46
  _MATRIX._serialized_end=96
  _CAMERAIMAGE._serialized_start=98
  _CAMERAIMAGE._serialized_end=198
  _OBSERVATION._serialized_start=201
  _OBSERVATION._serialized_end=335
# @@protoc_insertion_point(module_scope)
