# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: service.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'service.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from google.protobuf import struct_pb2 as google_dot_protobuf_dot_struct__pb2
import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rservice.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x0c\x63ommon.proto\"\x1d\n\x0bStepRequest\x12\x0e\n\x06\x61\x63tion\x18\x01 \x03(\x02\"\xb4\x01\n\x0cStepResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x0bobservation\x18\x03 \x01(\x0b\x32\x0c.Observation\x12\x0e\n\x06reward\x18\x04 \x01(\x02\x12\x12\n\nterminated\x18\x05 \x01(\x08\x12\x11\n\ttruncated\x18\x06 \x01(\x08\x12)\n\x08StepInfo\x18\x07 \x01(\x0b\x32\x17.google.protobuf.Struct\"\x0e\n\x0cResetRequest\"~\n\rResetResponse\x12\x0e\n\x06status\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12!\n\x0bobservation\x18\x03 \x01(\x0b\x32\x0c.Observation\x12)\n\x08StepInfo\x18\x04 \x01(\x0b\x32\x17.google.protobuf.Struct2Y\n\nEnvService\x12&\n\x05Reset\x12\r.ResetRequest\x1a\x0e.ResetResponse\x12#\n\x04Step\x12\x0c.StepRequest\x1a\r.StepResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'service_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_STEPREQUEST']._serialized_start=61
  _globals['_STEPREQUEST']._serialized_end=90
  _globals['_STEPRESPONSE']._serialized_start=93
  _globals['_STEPRESPONSE']._serialized_end=273
  _globals['_RESETREQUEST']._serialized_start=275
  _globals['_RESETREQUEST']._serialized_end=289
  _globals['_RESETRESPONSE']._serialized_start=291
  _globals['_RESETRESPONSE']._serialized_end=417
  _globals['_ENVSERVICE']._serialized_start=419
  _globals['_ENVSERVICE']._serialized_end=508
# @@protoc_insertion_point(module_scope)
