# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: metadrive/misc/nurec_interface/nre/grpc/protos/common.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n;metadrive/misc/nurec_interface/nre/grpc/protos/common.proto\x12\x16nre.grpc.protos.common\"\x07\n\x05\x45mpty\"2\n\x04Quat\x12\t\n\x01w\x18\x01 \x01(\x02\x12\t\n\x01x\x18\x02 \x01(\x02\x12\t\n\x01y\x18\x03 \x01(\x02\x12\t\n\x01z\x18\x04 \x01(\x02\"\'\n\x04Vec3\x12\t\n\x01x\x18\x01 \x01(\x02\x12\t\n\x01y\x18\x02 \x01(\x02\x12\t\n\x01z\x18\x03 \x01(\x02\"]\n\x04Pose\x12)\n\x03vec\x18\x01 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Vec3\x12*\n\x04quat\x18\x02 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Quat\"}\n\x0c\x44ynamicState\x12\x36\n\x10\x61ngular_velocity\x18\x01 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Vec3\x12\x35\n\x0flinear_velocity\x18\x02 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Vec3\"6\n\x04\x41\x41\x42\x42\x12\x0e\n\x06size_x\x18\x01 \x01(\x02\x12\x0e\n\x06size_y\x18\x02 \x01(\x02\x12\x0e\n\x06size_z\x18\x03 \x01(\x02\"N\n\nPoseAtTime\x12*\n\x04pose\x18\x01 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Pose\x12\x14\n\x0ctimestamp_us\x18\x02 \x01(\x06\"\x84\x01\n\x0bStateAtTime\x12\x14\n\x0ctimestamp_us\x18\x01 \x01(\x06\x12*\n\x04pose\x18\x02 \x01(\x0b\x32\x1c.nre.grpc.protos.common.Pose\x12\x33\n\x05state\x18\x03 \x01(\x0b\x32$.nre.grpc.protos.common.DynamicState\"?\n\nTrajectory\x12\x31\n\x05poses\x18\x01 \x03(\x0b\x32\".nre.grpc.protos.common.PoseAtTime\"\xb4\x01\n\tVersionId\x12\x12\n\nversion_id\x18\x01 \x01(\t\x12\x10\n\x08git_hash\x18\x02 \x01(\t\x12\x46\n\x10grpc_api_version\x18\x03 \x01(\x0b\x32,.nre.grpc.protos.common.VersionId.APIVersion\x1a\x39\n\nAPIVersion\x12\r\n\x05major\x18\x01 \x01(\r\x12\r\n\x05minor\x18\x02 \x01(\r\x12\r\n\x05patch\x18\x03 \x01(\r\"\x16\n\x14SessionRequestStatus\"*\n\x15\x41vailableScenesReturn\x12\x11\n\tscene_ids\x18\x01 \x03(\tb\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'metadrive.misc.nurec_interface.nre.grpc.protos.common_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _EMPTY._serialized_start=87
  _EMPTY._serialized_end=94
  _QUAT._serialized_start=96
  _QUAT._serialized_end=146
  _VEC3._serialized_start=148
  _VEC3._serialized_end=187
  _POSE._serialized_start=189
  _POSE._serialized_end=282
  _DYNAMICSTATE._serialized_start=284
  _DYNAMICSTATE._serialized_end=409
  _AABB._serialized_start=411
  _AABB._serialized_end=465
  _POSEATTIME._serialized_start=467
  _POSEATTIME._serialized_end=545
  _STATEATTIME._serialized_start=548
  _STATEATTIME._serialized_end=680
  _TRAJECTORY._serialized_start=682
  _TRAJECTORY._serialized_end=745
  _VERSIONID._serialized_start=748
  _VERSIONID._serialized_end=928
  _VERSIONID_APIVERSION._serialized_start=871
  _VERSIONID_APIVERSION._serialized_end=928
  _SESSIONREQUESTSTATUS._serialized_start=930
  _SESSIONREQUESTSTATUS._serialized_end=952
  _AVAILABLESCENESRETURN._serialized_start=954
  _AVAILABLESCENESRETURN._serialized_end=996
# @@protoc_insertion_point(module_scope)
